# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [8.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run archive

    - name: Generate Tag
      run: echo "release_tag=auto-release-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${{ env.release_tag }}
        files: build/app/outputs/flutter-apk/app-release.apk

    - name: Delete Older Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
